### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by addorange** [pionl/laravel-eloquent-position#1]
Hi Martin,

would you mind to allow Laravel 5.4 as a requirement? Or is there some breaking change that your package wouldn't work with Laravel 5.4?

Cheers,

Christian

**Comment by pionl** [comment]
Hi Christian,

thanks for the request. I've added also 5.4 to a composer (we can support multiple versions). Could you try install the dev-master (not release version) and confirm that works? Currently I don't have 5.4 project installed (and limited time). By the 5.3 => 5.4 changelog it should work :)

Thank you for the support,
Best regards,
Martin

**Comment by addorange** [comment]
Hi Martin,

seems to work :-). At least I could manage to work out my Vue.js-driven sorter on children elements powered by your package. If I will get to eventual issues, I willlet you know.

So many thanks for your quick response and your work.

Kind regards

Christian

**Comment by pionl** [comment]
Hi Christian, great :) Will make a release version. 

I thank you for the kind message. 

Have a great day
