### ISSUE TITLE
Reorder items

### ISSUE THREAD

**Issue by addorange** [pionl/laravel-eloquent-position#2]
Hi Martin,

I am reordering elements belonging to the same parent on the user interface and pass all the ordered elements to a controller. There I am iterating through them and want to set the position according to the positioning in the user interface. Therefore every passed element has a new property 'position'.

`foreach ($request->all() as $item) {
$contentElement = ContentElement::find($item['id']);
$contentElement->setPosition($item['position']);
$contentElement->save();
}`

But I does not work as I would expect, as not every contentElement gets the value from $item['position']. Some still stay on '0'.

Could you give me a hint how I could achieve that?

Kind regards

Christian

**Comment by pionl** [comment]
Hi Christian,

at this moment it's designed to support move from 1 position to different position (or prefill the last/first), it will not fetch all items and update the correct order. You are forcing your position (which is OK), but it will not fix already positions that are 0. For start you can run the `php artisian model:position` which will fix the order for all items. 

Or do you need to refresh the the full order after save? (which means you will get 0 from the 'user').

Best regards,
Martin


P.S: you should probably use `ContentElement::findOrFail` to prevent crash when entry doesn't exists.

**Comment by addorange** [comment]
Hi Martin,

thanks for the quick response. I tried to initialize the correct positioning on a seeder class and therefore called:

        // Initial ordering
        Artisan::call('model:position', [
            'model'=> \App\ContentElement::class
        ]);

But it appeared to not sort all of the content elements as several of them got position "0" and only some a proper value.

So, could there be a way to properly force the position? As I said I'm doing some sorting on the frontend and would like to persist this order to the respective content elements.

Ah, and thanks for the tip with `findOrFail`. Did miss that.

Cheers,

Christian

**Comment by pionl** [comment]
I'm not sure if I follow correctly. The command fails to change orders like: 0, 0, 2, 3, 5 to 1, 2, 3, 4, 5 ? If there is zero, it will be first when position command is called.

When you are setting position, it will check if you are moving from 1 to 5 and it will update only items within the range in a single query.

Could you try master version, I've added small improvement to the update command. In my case it updates correctly.

1. Update the package to master version (dev-master)
2. Call the command
3. Check the entries (all should have correct position set).
4. Use your UI

Another approach is to set the position as you are doing, but then call refresh. There are 2 options
1. I could add a new function that would accept parent keys to filter the artisan call - not to refresh whole table).
2. Or if you get all the items in the request (all items in group) I could create a class that would accept a list of items and it will update the position if not correctly.

Currently you can do this:
```php
foreach ($request->all() as $item) { 
       $contentElement = ContentElement::findOrFail($item['id']);
       $contentElement->setDisablePositionUpdateAttribute(true);
       $contentElement->setPosition($item['position'])
              ->save(); 
}

    // Reorder the entries
    Artisan::call('model:position', [
        'model'=> ContentElement::class
    ]);
```

On master you can do it:
```php
foreach ($request->all() as $item) { 
       ContentElement::findOrFail($item['id'])
            ->setDisablePositionUpdateAttribute(true)
              ->setPosition($item['position'])
              ->save(); 
}

    // Reorder the entries
    Artisan::call('model:position', [
        'model'=> ContentElement::class
    ]);
```
