### ISSUE TITLE
laravel 5.7.*

### ISSUE THREAD

**Issue by mariodro** [pionl/laravel-eloquent-position#4]
Hi, can you update to laravel 5.7?? 
thanks.

**Comment by wisusdev** [comment]
pion/laravel-eloquent-position v1.0.4 requires laravel/framework 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.* || 5.6.*

**Comment by elshobokshy** [comment]
I suppose it's never going to be available for laravel 6 ? Too bad

**Comment by pionl** [comment]
Hi, thanks for the issue. I've changed the composer requirement to. 5.* + I've added a hot fix. Please use 1.0.5 version.
