### ISSUE TITLE
Forking the package to accepts all laravel versions >= 5.1

### ISSUE THREAD

**Issue by elshobokshy** [pionl/laravel-eloquent-position#6]
I forked the package to accepts all laravel versions >= 5.1

https://github.com/elshobokshy/laravel-eloquent-position

I left the readme and everything else intact.

    composer require elshobokshy/laravel-eloquent-position

**Comment by pionl** [comment]
Hi, thanks for the confirmation. I've changed the composer requirement to. 5.* + I've added a hot fix. Please use 1.0.5 version.

**Comment by elshobokshy** [comment]
@pionl that won't work for any version > to 5. I'm using laravel 6. This issue should NOT be closed.

**Comment by pionl** [comment]
@elshobokshy did not catch you need 6.*. 

1.0.6 released.

**Comment by elshobokshy** [comment]
@pionl 

    Call to undefined method Illuminate\Events\Dispatcher::fire()

The fire method was renamed. It doesn't work for Laravel 6.

**Comment by pionl** [comment]
ok thank, I'll update the code

**Comment by elshobokshy** [comment]
@pionl and kindly test it before confirming that it works. Thank you for your contribution to opensource!
