### ISSUE TITLE
Delete an item doesn't update the positions

### ISSUE THREAD

**Issue by elshobokshy** [pionl/laravel-eloquent-position#7]
When an item is deleted, the positions stays the same. Imagine I have 3 entries in the table thus having 3 positions. So when I delete the position number 2, the upcoming positions do not change and start from 2, but I still have positions 1 and 3. Any idea how to fix this?

**Comment by elshobokshy** [comment]
I just had to recall this piece of code right after my delete 👍 

```
    // Reorder the entries
    Artisan::call('model:position', [
        'model'=> MyClass::class
    ]);
```

**Comment by pionl** [comment]
Should be handled by `PositionObserver`, should be easy to implement (only if you use $model->delete())

**Comment by pionl** [comment]
Fixed
